openapi: 3.0.1
info:
  title: Ad-Server-Service
  version: v0
servers:
  - url: 'http://localhost:6107'
    description: ad server
paths:
  /ad:
    get:
      tags:
        - adserver-controller
      operationId: getAd
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
