openapi: 3.0.1
info:
  title: U1-M4-Challenge-Downey-Stephen
  version: v0
servers:
  - url: 'http://localhost:8080'
    description: Generated server url
paths:
  /magic:
    post:
      tags:
        - magic-8-ball-controller
      operationId: getAnswer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Answer'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CustomErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomErrorResponse'
  /word:
    get:
      tags:
        - word-controller
      operationId: getDefinition
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Definition'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CustomErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomErrorResponse'
  /quote:
    get:
      tags:
        - quote-controller
      operationId: getRandomQuote
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Quote'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CustomErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomErrorResponse'
components:
  schemas:
    CustomErrorResponse:
      type: object
      properties:
        errorMessage:
          type: string
        status:
          type: integer
          format: int32
        errorCode:
          type: string
        localDateTime:
          type: string
          format: date-time
    Question:
      required:
        - question
      type: object
      properties:
        question:
          type: string
    Answer:
      type: object
      properties:
        id:
          type: string
        question:
          type: string
        answer:
          type: string
    Definition:
      type: object
      properties:
        id:
          type: string
        word:
          type: string
        definition:
          type: string
    Quote:
      type: object
      properties:
        id:
          type: string
        author:
          type: string
        quote:
          type: string
